using Website_Cosmetics.Models;
using Website_Cosmetics.Data;

namespace Website_Cosmetics.Services;

public class DbInitializer
{
    public static void Initialize(ApplicationDbContext context)
    {
        // Chỉ seed khi database trống - KHÔNG xóa dữ liệu cũ
        // Nếu đã có dữ liệu, bỏ qua seeding
        if (context.Products.Any() || context.Brands.Any() || context.Categories.Any())
        {
            // Database đã có dữ liệu, không cần seed
            return;
        }

        var now = DateTime.Now;

        // Add sample brands (BrandId will be auto-generated by IDENTITY)
        var brands = new Brand[]
        {
            new Brand { Name = "L'Oréal", Country = "France", IsActive = true, CreatedAt = now, UpdatedAt = now },
            new Brand { Name = "Maybelline", Country = "USA", IsActive = true, CreatedAt = now, UpdatedAt = now },
            new Brand { Name = "MAC Cosmetics", Country = "Canada", IsActive = true, CreatedAt = now, UpdatedAt = now },
            new Brand { Name = "NARS", Country = "France", IsActive = true, CreatedAt = now, UpdatedAt = now },
            new Brand { Name = "Fenty Beauty", Country = "USA", IsActive = true, CreatedAt = now, UpdatedAt = now }
        };

        // Chỉ add brands nếu chưa tồn tại
        var existingBrands = context.Brands.Select(b => b.Name).ToList();
        var newBrands = brands.Where(b => !existingBrands.Contains(b.Name)).ToList();
        if (newBrands.Any())
        {
            context.Brands.AddRange(newBrands);
            context.SaveChanges();
        }

        // Add sample categories (CategoryId will be auto-generated by IDENTITY)
        var categories = new Category[]
        {
            new Category { Name = "Lipstick", Description = "Lipstick products in various finishes", IsActive = true, CreatedAt = now, UpdatedAt = now },
            new Category { Name = "Eye Shadow", Description = "Eye shadow palettes and singles", IsActive = true, CreatedAt = now, UpdatedAt = now },
            new Category { Name = "Blush", Description = "Powder and cream blush products", IsActive = true, CreatedAt = now, UpdatedAt = now },
            new Category { Name = "Foundation", Description = "Foundation for all skin types", IsActive = true, CreatedAt = now, UpdatedAt = now },
            new Category { Name = "Powder", Description = "Setting and finishing powders", IsActive = true, CreatedAt = now, UpdatedAt = now }
        };

        // Chỉ add categories nếu chưa tồn tại
        var existingCategories = context.Categories.Select(c => c.Name).ToList();
        var newCategories = categories.Where(c => !existingCategories.Contains(c.Name)).ToList();
        if (newCategories.Any())
        {
            context.Categories.AddRange(newCategories);
            context.SaveChanges();
        }

        // Lấy lại brands và categories để link với products
        var allBrands = context.Brands.ToList();
        var allCategories = context.Categories.ToList();

        // Add sample products
        var products = new Product[]
        {
            // Most Loved Products (8 products)
            new Product
            {
                Name = "Maybelline SuperStay Matte Ink",
                Slug = "maybelline-superstay-matte-ink",
                BasePrice = 15.00m,
                Description = "Long-lasting matte lipstick with up to 16 hours wear.",
                Ingredients = "Isododecane, Dimethicone, Silica.",
                IsActive = true,
                BrandId = allBrands.FirstOrDefault(b => b.Name == "Maybelline")?.BrandId,
                CategoryId = allCategories.FirstOrDefault(c => c.Name == "Lipstick")?.CategoryId,
                CreatedAt = now.AddDays(-30),
                UpdatedAt = now
            },
            new Product
            {
                Name = "Maybelline SuperStay Matte Ink",
                Slug = "maybelline-superstay-matte-ink",
                BasePrice = 15.00m,
                Description = "Long-lasting matte lipstick with up to 16 hours wear.",
                Ingredients = "Isododecane, Dimethicone, Silica.",
                IsActive = true,
                BrandId = allBrands.FirstOrDefault(b => b.Name == "Maybelline")?.BrandId,
                CategoryId = allCategories.FirstOrDefault(c => c.Name == "Lipstick")?.CategoryId,
                CreatedAt = now.AddDays(-30),
                UpdatedAt = now
            },
            new Product
            {
                Name = "L'Oréal Rouge Signature Liquid Lipstick",
                Slug = "loreal-rouge-signature",
                BasePrice = 12.00m,
                Description = "Lightweight matte liquid lipstick with comfortable wear.",
                Ingredients = "Dimethicone, Isododecane, Silica.",
                IsActive = true,
                BrandId = allBrands.FirstOrDefault(b => b.Name == "L'Oréal")?.BrandId,
                CategoryId = allCategories.FirstOrDefault(c => c.Name == "Lipstick")?.CategoryId,
                CreatedAt = now.AddDays(-28),
                UpdatedAt = now
            },
            new Product
            {
                Name = "NARS Afterglow Lip Balm",
                Slug = "nars-afterglow-lip-balm",
                BasePrice = 28.00m,
                Description = "Luxurious tinted lip balm with natural finish.",
                Ingredients = "Natural oils, Vitamin E, Pigments.",
                IsActive = true,
                BrandId = allBrands.FirstOrDefault(b => b.Name == "NARS")?.BrandId,
                CategoryId = allCategories.FirstOrDefault(c => c.Name == "Lipstick")?.CategoryId,
                CreatedAt = now.AddDays(-25),
                UpdatedAt = now
            },
            new Product
            {
                Name = "MAC Powder Kiss Lipstick",
                Slug = "mac-powder-kiss",
                BasePrice = 22.00m,
                Description = "Soft matte lipstick with powder-like finish.",
                Ingredients = "Silica, Dimethicone, Color pigments.",
                IsActive = true,
                BrandId = allBrands.FirstOrDefault(b => b.Name == "MAC Cosmetics")?.BrandId,
                CategoryId = allCategories.FirstOrDefault(c => c.Name == "Lipstick")?.CategoryId,
                CreatedAt = now.AddDays(-22),
                UpdatedAt = now
            },
            new Product
            {
                Name = "L'Oréal Paradise Enchanted Palette",
                Slug = "loreal-paradise-palette",
                BasePrice = 18.00m,
                Description = "12-shade eyeshadow palette with warm tones.",
                Ingredients = "Talc, Mica, Dimethicone.",
                IsActive = true,
                BrandId = allBrands.FirstOrDefault(b => b.Name == "L'Oréal")?.BrandId,
                CategoryId = allCategories.FirstOrDefault(c => c.Name == "Eye Shadow")?.CategoryId,
                CreatedAt = now.AddDays(-20),
                UpdatedAt = now
            },
            new Product
            {
                Name = "NARS Orgasm Blush",
                Slug = "nars-orgasm-blush",
                BasePrice = 32.00m,
                Description = "Iconic peachy-pink blush with golden shimmer.",
                Ingredients = "Talc, Nylon-12, Dimethicone.",
                IsActive = true,
                BrandId = allBrands.FirstOrDefault(b => b.Name == "NARS")?.BrandId,
                CategoryId = allCategories.FirstOrDefault(c => c.Name == "Blush")?.CategoryId,
                CreatedAt = now.AddDays(-18),
                UpdatedAt = now
            },
            new Product
            {
                Name = "Fenty Cheeks Out Cream Blush",
                Slug = "fenty-cheeks-out",
                BasePrice = 26.00m,
                Description = "Cream blush stick with natural, blendable finish.",
                Ingredients = "Dimethicone, Silica, Color pigments.",
                IsActive = true,
                BrandId = allBrands.FirstOrDefault(b => b.Name == "Fenty Beauty")?.BrandId,
                CategoryId = allCategories.FirstOrDefault(c => c.Name == "Blush")?.CategoryId,
                CreatedAt = now.AddDays(-15),
                UpdatedAt = now
            },
            new Product
            {
                Name = "Maybelline Lash Sensational Mascara",
                Slug = "maybelline-lash-sensational",
                BasePrice = 9.00m,
                Description = "Volumizing mascara for longer, fuller lashes.",
                Ingredients = "Paraffin, Beeswax, Carnauba wax.",
                IsActive = true,
                BrandId = allBrands.FirstOrDefault(b => b.Name == "Maybelline")?.BrandId,
                CategoryId = allCategories.FirstOrDefault(c => c.Name == "Eye Shadow")?.CategoryId,
                CreatedAt = now.AddDays(-12),
                UpdatedAt = now
            },
            
            // Special Deals Products (8 products)
            new Product
            {
                Name = "MAC Studio Fix Fluid SPF15",
                Slug = "mac-studio-fix-fluid",
                BasePrice = 35.00m,
                Description = "Full coverage foundation with oil control.",
                Ingredients = "Water, Cyclopentasiloxane, Talc.",
                IsActive = true,
                BrandId = allBrands.FirstOrDefault(b => b.Name == "MAC Cosmetics")?.BrandId,
                CategoryId = allCategories.FirstOrDefault(c => c.Name == "Foundation")?.CategoryId,
                CreatedAt = now.AddDays(-10),
                UpdatedAt = now.AddDays(-1)
            },
            new Product
            {
                Name = "Fenty Beauty Pro Filt'r Powder",
                Slug = "fenty-pro-filtr-powder",
                BasePrice = 36.00m,
                Description = "Soft matte longwear setting powder.",
                Ingredients = "Silica, Dimethicone, Mica.",
                IsActive = true,
                BrandId = allBrands.FirstOrDefault(b => b.Name == "Fenty Beauty")?.BrandId,
                CategoryId = allCategories.FirstOrDefault(c => c.Name == "Powder")?.CategoryId,
                CreatedAt = now.AddDays(-8),
                UpdatedAt = now.AddDays(-1)
            },
            new Product
            {
                Name = "L'Oréal Infallible 24H Foundation",
                Slug = "loreal-infallible-24h",
                BasePrice = 16.00m,
                Description = "24-hour wear foundation with full coverage.",
                Ingredients = "Cyclopentasiloxane, Dimethicone, Titanium Dioxide.",
                IsActive = true,
                BrandId = allBrands.FirstOrDefault(b => b.Name == "L'Oréal")?.BrandId,
                CategoryId = allCategories.FirstOrDefault(c => c.Name == "Foundation")?.CategoryId,
                CreatedAt = now.AddDays(-6),
                UpdatedAt = now.AddDays(-2)
            },
            new Product
            {
                Name = "Maybelline Baby Skin Primer",
                Slug = "maybelline-baby-skin",
                BasePrice = 8.00m,
                Description = "Pore-minimizing primer for smooth skin.",
                Ingredients = "Dimethicone, Silica, Polymethylsilsesquioxane.",
                IsActive = true,
                BrandId = allBrands.FirstOrDefault(b => b.Name == "Maybelline")?.BrandId,
                CategoryId = allCategories.FirstOrDefault(c => c.Name == "Foundation")?.CategoryId,
                CreatedAt = now.AddDays(-5),
                UpdatedAt = now.AddDays(-1)
            },
            new Product
            {
                Name = "MAC Studio Face & Body Foundation",
                Slug = "mac-studio-face-body",
                BasePrice = 38.00m,
                Description = "Lightweight, natural-looking foundation.",
                Ingredients = "Water, Glycerin, Dimethicone.",
                IsActive = true,
                BrandId = allBrands.FirstOrDefault(b => b.Name == "MAC Cosmetics")?.BrandId,
                CategoryId = allCategories.FirstOrDefault(c => c.Name == "Foundation")?.CategoryId,
                CreatedAt = now.AddDays(-4),
                UpdatedAt = now.AddDays(-1)
            },
            new Product
            {
                Name = "NARS Radiant Creamy Concealer",
                Slug = "nars-radiant-concealer",
                BasePrice = 31.00m,
                Description = "Multi-action concealer with high coverage.",
                Ingredients = "Water, Dimethicone, Glycerin.",
                IsActive = true,
                BrandId = allBrands.FirstOrDefault(b => b.Name == "NARS")?.BrandId,
                CategoryId = allCategories.FirstOrDefault(c => c.Name == "Foundation")?.CategoryId,
                CreatedAt = now.AddDays(-3),
                UpdatedAt = now.AddDays(-1)
            },
            new Product
            {
                Name = "L'Oréal Infallible Setting Powder",
                Slug = "loreal-infallible-powder",
                BasePrice = 11.00m,
                Description = "Long-lasting oil-control setting powder.",
                Ingredients = "Talc, Silica, Mica.",
                IsActive = true,
                BrandId = allBrands.FirstOrDefault(b => b.Name == "L'Oréal")?.BrandId,
                CategoryId = allCategories.FirstOrDefault(c => c.Name == "Powder")?.CategoryId,
                CreatedAt = now.AddDays(-2),
                UpdatedAt = now
            },
            new Product
            {
                Name = "Maybelline Fit Me Powder",
                Slug = "maybelline-fit-me-powder",
                BasePrice = 7.00m,
                Description = "Natural, oil-controlling finishing powder.",
                Ingredients = "Talc, Dimethicone, Nylon-12.",
                IsActive = true,
                BrandId = allBrands.FirstOrDefault(b => b.Name == "Maybelline")?.BrandId,
                CategoryId = allCategories.FirstOrDefault(c => c.Name == "Powder")?.CategoryId,
                CreatedAt = now.AddDays(-1),
                UpdatedAt = now
            }
        };

        // Chỉ add products nếu chưa tồn tại
        var existingProductNames = context.Products.Select(p => p.Name).ToList();
        var newProducts = products.Where(p => !existingProductNames.Contains(p.Name) && p.BrandId.HasValue && p.CategoryId.HasValue).ToList();
        if (newProducts.Any())
        {
            context.Products.AddRange(newProducts);
            context.SaveChanges();

            // Add product images cho products mới
            var productImages = new List<ProductImage>();
            for (int i = 0; i < newProducts.Count; i++)
            {
                // Products 0-7: Most Loved (lipstick, eyeshadow, blush) - use img-cart-lip
                // Products 8-15: Special Deals (foundation, powder) - use img-cart-brush  
                string imageUrl = i < 8 
                    ? "/public/images/products/img-cart-lip.png" 
                    : "/public/images/products/img-cart-brush.png";
                    
                productImages.Add(new ProductImage
                {
                    ProductId = newProducts[i].ProductId,
                    Url = imageUrl,
                    ImageType = "cover",
                    AltText = newProducts[i].Name,
                    CreatedAt = now
                });
            }

            if (productImages.Any())
            {
                context.ProductImages.AddRange(productImages);
                context.SaveChanges();
            }
        }
    }
}

