-- Script tạo các bảng cho hệ thống Authentication
-- Database: Website_Cosmetics

-- Tạo bảng Roles
CREATE TABLE Roles (
    UID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    RoleName NVARCHAR(50) NOT NULL UNIQUE,
    Description NVARCHAR(255),
    IsActive BIT NOT NULL DEFAULT 1,
    CreatedAt DATETIME2(7) NOT NULL DEFAULT GETDATE(),
    UpdatedAt DATETIME2(7) NOT NULL DEFAULT GETDATE()
);

-- Tạo bảng Users
CREATE TABLE Users (
    UID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Username NVARCHAR(50) NOT NULL UNIQUE,
    Email NVARCHAR(100) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(255) NOT NULL,
    FirstName NVARCHAR(50),
    LastName NVARCHAR(50),
    PhoneNumber NVARCHAR(20),
    IsEmailConfirmed BIT NOT NULL DEFAULT 0,
    IsActive BIT NOT NULL DEFAULT 1,
    CreatedAt DATETIME2(7) NOT NULL DEFAULT GETDATE(),
    UpdatedAt DATETIME2(7) NOT NULL DEFAULT GETDATE()
);

-- Tạo bảng UserRoles
CREATE TABLE UserRoles (
    UID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserUID UNIQUEIDENTIFIER NOT NULL,
    RoleUID UNIQUEIDENTIFIER NOT NULL,
    CreatedAt DATETIME2(7) NOT NULL DEFAULT GETDATE(),
    UpdatedAt DATETIME2(7) NOT NULL DEFAULT GETDATE(),
    FOREIGN KEY (UserUID) REFERENCES Users(UID) ON DELETE CASCADE,
    FOREIGN KEY (RoleUID) REFERENCES Roles(UID) ON DELETE CASCADE,
    UNIQUE(UserUID, RoleUID)
);

-- Tạo bảng PasswordResetTokens
CREATE TABLE PasswordResetTokens (
    UID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserUID UNIQUEIDENTIFIER NOT NULL,
    Token NVARCHAR(255) NOT NULL UNIQUE,
    ExpiresAt DATETIME2(7) NOT NULL,
    IsUsed BIT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2(7) NOT NULL DEFAULT GETDATE(),
    UpdatedAt DATETIME2(7) NOT NULL DEFAULT GETDATE(),
    FOREIGN KEY (UserUID) REFERENCES Users(UID) ON DELETE CASCADE
);

-- Tạo bảng EmailConfirmationTokens
CREATE TABLE EmailConfirmationTokens (
    UID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserUID UNIQUEIDENTIFIER NOT NULL,
    Token NVARCHAR(255) NOT NULL UNIQUE,
    ExpiresAt DATETIME2(7) NOT NULL,
    IsUsed BIT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2(7) NOT NULL DEFAULT GETDATE(),
    UpdatedAt DATETIME2(7) NOT NULL DEFAULT GETDATE(),
    FOREIGN KEY (UserUID) REFERENCES Users(UID) ON DELETE CASCADE
);

-- Tạo indexes để tối ưu hiệu suất
CREATE INDEX IX_Users_Email ON Users(Email);
CREATE INDEX IX_Users_Username ON Users(Username);
CREATE INDEX IX_PasswordResetTokens_Token ON PasswordResetTokens(Token);
CREATE INDEX IX_PasswordResetTokens_UserUID ON PasswordResetTokens(UserUID);
CREATE INDEX IX_EmailConfirmationTokens_Token ON EmailConfirmationTokens(Token);
CREATE INDEX IX_EmailConfirmationTokens_UserUID ON EmailConfirmationTokens(UserUID);
CREATE INDEX IX_UserRoles_UserUID ON UserRoles(UserUID);
CREATE INDEX IX_UserRoles_RoleUID ON UserRoles(RoleUID);
